env:
  global:
    - CODECOV_TOKEN="7d49808f-3f5f-4652-a38a-6eff26aa92e4"

language: c
sudo: false # only for faster builds

# Install lib gtk 3
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libgtk-3-dev

script:
  - make
  - clang -coverage -O0 main.c -o main
  - ./main
  - gcov main.c

after_success:
  - bash <(curl -s https://codecov.io/bash)
